### ISSUE TITLE
Indent style syntax seems to be possible.

### ISSUE THREAD

**Issue by mull** [mathias/boot-sassc#16]
Hi. From the README:

> The sassc executable only compiles SCSS syntax, not the indent-style Sass syntax!

However that seemed wrong to me, so I tested both sassc and boot-sassc and each of them works just fine with SASS syntax. Tested with this:

``` sass
$font-stack:    Helvetica, sans-serif
$primary-color: #333

body
  font: 100% $font-stack
  color: $primary-color
  background-color: #eee
```

Output:

``` css
body {
  font: 100% Helvetica, sans-serif;
  color: #333;
  background-color: #eee; }
```
